export const SESSION_AUTHENTICATED = "SESSION_AUTHENTICATED";
export const SESSION_SIGNED_OUT = "SESSION_SIGNED_OUT";
export const SESSION_AUTHENTICATION_STARTED = "SESSION_AUTHENTICATION_STARTED";
export const SESSION_AUTHENTICATION_FAILED = "SESSION_AUTHENTICATION_FAILED";
